export enum SocketEventType {
  CREATE_DB_CONN_REQ = 'CREATE_DB_CONN_REQUEST',
  CREATE_DB_CONN_RESPONSE = 'CREATE_DB_CONN_RESPONSE',
  DISCONNCT_DB_CON_RESPONSE = 'DISCONNECT_DB_CON_RESPONSE',
  ISSUE_DB_CMD_REQ = 'ISSUE_DB_CMD_REQUEST',
  ISSUE_DB_CMD_RESPONSE = 'ISSUE_DB_CMD_RESPONSE',
}
